apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 30s
    count: 3
    successCondition: result == "healthy"
    failureLimit: 2
    provider:
      web:
        url: "http://sentinel-service.default.svc:8080/version"
        jsonPath: "{$.status}"
