apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 30s
    count: 3
    successCondition: result == "ok"
    failureLimit: 3
    provider:
      web:
        url: "http://sentinel-service.default.svc:8080/actuator/health"
        jsonPath: "{$.status}"
