apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-app
  labels:
    app: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      containers:
        - name: sentinel-container
          image: 408834627625.dkr.ecr.ap-south-1.amazonaws.com/sentinel-app:v1
          ports:
            - containerPort: 8080

          # Phase 4 Guardrails: Resource Management
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          # Phase 4 Guardrails: Health Checks
          # Liveness:
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10

          # Readiness:
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 5

      imagePullSecrets:
        - name: ecr-registry-key