apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sentinel-app
spec:
  replicas: 2
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 1
      steps:
      - setWeight: 20
      - pause: {duration: 1m}
      - setWeight: 50
      - pause: {duration: 1m}
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      containers:
      - name: sentinel-container
        image: 408834627625.dkr.ecr.ap-south-1.amazonaws.com/sentinel-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: ecr-registry-key
