name: Sentinel CI/CD

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests
          ls -R target/
        working-directory: ./sentinel-app

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: sentinel-app
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build --no-cache \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -f Dockerfile \
            sentinel-app/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "REGISTRY=$ECR_REGISTRY" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/sentinel-app:${{ github.run_number }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Configure AWS CLI on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if ! command -v aws &> /dev/null; then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              sudo apt install unzip -y -q
              unzip -q awscliv2.zip
              sudo ./aws/install
              rm -rf aws awscliv2.zip
            fi
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set region ap-south-1

            
            if ! command -v kubectl-argo-rollouts &> /dev/null; then
              curl -LO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64
              chmod +x ./kubectl-argo-rollouts-linux-amd64
              sudo mv ./kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts
            fi

      - name: Deploy to K3s via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! -d ~/Sentinel-Canary ]; then
              git clone https://github.com/krishjj8/Sentinel-Canary.git ~/Sentinel-Canary
            fi

            aws ecr get-login-password --region ap-south-1 \
              | sudo kubectl create secret docker-registry ecr-registry-key \
              --docker-server=408834627625.dkr.ecr.ap-south-1.amazonaws.com \
              --docker-username=AWS \
              --docker-password=$(aws ecr get-login-password --region ap-south-1) \
              --dry-run=client -o yaml | sudo kubectl apply -f -

            cd ~/Sentinel-Canary
            git pull origin main
            sed -i "s|image: .*sentinel-app:.*|image: ${{ env.REGISTRY }}/sentinel-app:${{ env.IMAGE_TAG }}|" k8s/rollout.yaml
            sudo kubectl apply -f k8s/rollout.yaml
            sudo kubectl apply -f k8s/service.yaml
            sudo kubectl argo rollouts status sentinel-app --timeout=300s
